config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "reconstructions#index"
  # Sidekiq web config
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
  end

  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }
  resources :reconstructions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reconstruction.rb
class Reconstruction < ApplicationRecord
  require 'matrix'

  # Relationships
  belongs_to :user
  has_one_attached :signal_file
  has_one_attached :img

  # Callbacks
  after_create :set_fields

  def set_fields
    self.rec_begin = DateTime.now
    save
  end

  def file_url
    Rails.application.routes.url_helpers.rails_blob_path(signal_file, disposition: 'attachment', only_path: true)
  end

  def cgne
    File.open('processing/signal.txt', 'w') do |f|
      f.write(signal_file.download.gsub(',', '.'))
    end

    system('python processing/reconstruct.py')

    self.rec_end = DateTime.now
    self.size = 60
    file = File.open(Rails.root.join(Dir[File.join('processing/', '*.*')].max_by(&File.method(:ctime))))
    self.img.attach(io: file, filename: 'reconstruction.png')
    save
  end

  def fista
    self.rec_end = DateTime.now
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relationships
  has_many :reconstruction

  # Validations
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/reconstructions_controller.rb
class ReconstructionsController < ApplicationController
  before_action :set_reconstruction, only: [:show, :edit, :update, :destroy]

  # GET /reconstructions
  # GET /reconstructions.json
  def index
    @reconstructions = Reconstruction.where(user_id: current_user.id)
  end

  # GET /reconstructions/1
  # GET /reconstructions/1.json
  def show
  end

  # GET /reconstructions/new
  def new
    @reconstruction = Reconstruction.new
  end

  # GET /reconstructions/1/edit
  def edit
  end

  # POST /reconstructions
  # POST /reconstructions.json
  def create
    params[:reconstruction][:user_id] = current_user.id
    @reconstruction = Reconstruction.new(reconstruction_params)

    respond_to do |format|
      if @reconstruction.save
        ReconstructionWorker.perform_async(@reconstruction.id)
        format.html { redirect_to @reconstruction, notice: 'Reconstrução criada e enfileirada pra processamento' }
        format.json { render :show, status: :created, location: @reconstruction }
      else
        format.html { render :new }
        format.json { render json: @reconstruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reconstructions/1
  # PATCH/PUT /reconstructions/1.json
  def update
  end

  # DELETE /reconstructions/1
  # DELETE /reconstructions/1.json
  def destroy
    @reconstruction.destroy
    respond_to do |format|
      format.html { redirect_to reconstructions_url, notice: 'Reconstrução excluída' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reconstruction
      @reconstruction = Reconstruction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reconstruction_params
      params.require(:reconstruction).permit(:algorithm, :rec_begin, :rec_end, :size, :iteractions, :signal_file, :user_id)
    end

    def process_signal
      str_signal = signal_file.download
      self.signal = str_signal.split("\r\n")
      save
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :sign_up_params, only: [:create]
  before_action :account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reconstructions_helper.rb
module ReconstructionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DISProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p id="notice" class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <p class="navbar-text pull-right">

    <% if user_signed_in? %>
      Logado como: <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% end %>
  </body>
</html>

app/views/reconstructions/_form.html.erb
<%= form_with(model: reconstruction, local: true, html: {class: "col s12 create_reconstruction"}) do |form| %>
  <% if reconstruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reconstruction.errors.count, "error") %> prohibited this reconstruction from being saved:</h2>

      <ul>
      <% reconstruction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Algoritmo' %>
    <%= form.select(:algorithm, [['CGNE', '1'], ['FISTA', '2']]) %>
  </div>

  <div class="field">
    <%= form.label 'Sinal' %>
    <%= form.file_field :signal_file %>
  </div>

  <div class="field">
    <%= form.hidden_field :signal %>
  </div>

  <div class="field">
    <%= form.hidden_field :proc_signal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reconstructions/edit.html.erb
<h1>Editar reconstrução</h1>

<p> Não é possível editar reconstruções, se desejar crie outra </p>

<%= link_to 'Show', @reconstruction %> |
<%= link_to 'Voltar', reconstructions_path %>

app/views/reconstructions/index.html.erb
<h1>Reconstruções</h1>

<table>
  <thead>
    <tr>
      <th>Algoritmo</th>
      <th>Início da reconstrução</th>
      <th>Fim da reconstrução</th>
      <th>Tamanho da Imagem</th>
      <th>Iterações</th>
      <th>Sinal</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reconstructions.each do |reconstruction| %>
      <tr>
        <% if reconstruction.algorithm == 1 %>
          <td>CGNE</td>
        <% else %>
          <td>FISTA</td>
        <% end %>
        <td><%= reconstruction.rec_begin.strftime("%d/%m/%Y - %H:%M:%S") %></td>
        <td><%= reconstruction.rec_end.strftime("%d/%m/%Y - %H:%M:%S") if reconstruction.rec_end %></td>
        <td><%= reconstruction.size %></td>
        <td><%= reconstruction.iteractions %></td>
        <td><%= link_to reconstruction.signal_file.blob.filename.to_s, rails_blob_path(reconstruction.signal_file, disposition: 'attachment') %></td>
        <td><%= link_to reconstruction.img.blob.filename.to_s, rails_blob_path(reconstruction.img, disposition: 'attachment') if reconstruction.img.attached? %></td>
        <td><%= link_to 'Mostrar', reconstruction %></td>
        <td><%= link_to 'Deletar', reconstruction, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Reconstruir um sinal', new_reconstruction_path %>

app/views/reconstructions/new.html.erb
<h1>Reconstruir um sinal</h1>

<%= render 'form', reconstruction: @reconstruction %>

<%= link_to 'Voltar', reconstructions_path %>

app/views/reconstructions/show.html.erb
<p>
  <strong>Algoritmo:</strong>
  <%= @reconstruction.algorithm %>
</p>

<p>
  <strong>Início da reconstrução:</strong>
  <%= @reconstruction.rec_begin %>
</p>

<p>
  <strong>Fim da reconstrução:</strong>
  <%= @reconstruction.rec_end %>
</p>

<p>
  <strong>Tamanho da Imagem:</strong>
  <%= @reconstruction.size %>
</p>

<p>
  <strong>Iterações:</strong>
  <%= @reconstruction.iteractions %>
</p>

<p>
  <strong>Sinal utilizado:</strong>
  <%= link_to @reconstruction.signal_file.blob.filename.to_s, rails_blob_path(@reconstruction.signal_file, disposition: 'attachment') %>
</p>

<p>
  <strong>Imagem reconstruida:</strong>
  <%= link_to @reconstruction.img.blob.filename.to_s, rails_blob_path(@reconstruction.img, disposition: 'attachment') if @reconstruction.img.attached? %>
</p>

<%= link_to 'Voltar', reconstructions_path %>